# Generated by Django 3.1.4 on 2020-12-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='post',
        ),
    ]
