# Generated by Django 3.1.4 on 2021-01-10 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_eventcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcomment',
            old_name='text_comment',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_comment', to='app.eventmodel'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
