# Generated by Django 3.1.4 on 2021-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210110_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='number_of_comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
